use_daos_toolkit: true
daos_toolkit:
  substrate:
    url: ""
  dt_id: '0'
  device_topic_name: ''
  device_account_mnemonic: '' #to be used in logging
  use_acl: true
  acl:
    acl_topic_name: ''
  use_action_logger: true
  action_logger:
    use_pinata: true
    pinata:
      api: ""
      secret_api: ""
